version: '3'
services:
  api:
    image: node:14.15.1
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - $API_PORT:$API_PORT
    environment:
      API_PORT: $API_PORT
    networks:
      - api_net
    restart: always
networks:
  api_net:    

    