version: '3'
services:
  api:
    build: 
      context: ./docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - $API_PORT:$API_PORT
    environment:
      API_PORT: $API_PORT
    networks:
      - api
    restart: always
    

    