version: '3.8'
services:
  api:
    image: node:14.15.1
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      API_PORT: $API_PORT
    networks:
      - api_net
      - database
    restart: always
  database:
    image: postgres:13
    restart: always
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_NAME
    networks:
      - database
    volumes:
      - ./db:/var/lib/postgresql/data
networks:
  api_net:
  database:

    